[theme]
primaryColor = "#6366F1"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "info"

[server]
enableXsrfProtection = true
headless = true
runOnSave = true

[ui]
hideTopBar = false
hideSidebarNav = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
